name = "intra"
account_id = "eed296214f8b8aa38533e38843f88aff"
main = ".open-next/worker.js"
compatibility_date = "2025-05-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
API_URL = "https://intra-api.nobelcapital.workers.dev"
USE_D1_USERS = "true"

[[services]]
binding = "INTRA_API"
service = "intra-api"
