name = "intra"
main = ".open-next/worker.js"
compatibility_date = "2025-05-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
API_URL = "https://intra-api.rafaelciaravolo.workers.dev"
INTERNAL_API_SECRET = "dev-perf-secret-2026"

[[services]]
binding = "INTRA_API"
service = "intra-api"
